### REQUIRED
# The namespace of the collection. This can be a company/brand/organization or product namespace under which all
# content lives. May only contain alphanumeric lowercase characters and underscores. Namespaces cannot start with
# underscores or numbers and cannot contain consecutive underscores
namespace: mahdishariat
name: shared_tasks
version: 1.0.0
readme: README.md
authors:
  - mahdishariat <mahdishariat@outlook.com>
description: A collection of tasks for the Galaxy project
license:
  - GPL-2.0-or-later
tags:
  - backup
  - restore
  - file_transfer
  - upload_s3
dependencies: {}
repository: https://github.com/mahdishariatzade/ansible-roles
documentation: https://github.com/mahdishariatzade/ansible-roles
homepage: https://github.com/mahdishariatzade/ansible-roles
issues: https://github.com/mahdishariatzade/ansible-roles/issues
build_ignore: []
